version: '3.5'
services:
  front-end:
    image: 'nicholasadamou/front-end:latest'
    container_name: front-end
    environment:
      - PERSON_SERVICE_HOST=person-service
      - PERSON_SERVICE_PORT=5445
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/opt/app'
      - /opt/app/node_modules
    ports:
      - '3001:3000'
    networks:
      - interview
networks:
  interview:
    name: interview
