import React from 'react';

import { Redirect } from 'react-router-dom';

import Cookies from 'universal-cookie';

import jwtDecode from 'jwt-decode';

import Loading from '../../components/Loading';

import { TOKEN } from '../../api/constants';

const cookies = new Cookies();

const Callback = (props) => {
	const [isLoading, setIsLoading] = React.useState(true);

	React.useEffect(() => {
		TOKEN.remove();

		// TODO: Verify the JWT token generated by Auth0.
		// TODO: Then, proceed to base route (/).

		setIsLoading(false);
	}, [])

	if (isLoading) {
		return <Loading />;
	}

	return <Redirect to="/" />;
}

export default Callback;
